Set FontFamily "JetBrainsMono NF"
Set FontSize 14
Set Width 1400
Set Height 760
Set Padding 8
Set Theme { "name": "amtr", "background": "#0d0f13", "foreground": "#aab1bd", "black": "#0d0f13", "red": "#e06c75", "green": "#98c379", "yellow": "#e5c07b", "blue": "#61afef", "magenta": "#c678dd", "cyan": "#56b6c2", "white": "#aab1bd", "brightBlack": "#5c6370", "brightRed": "#e06c75", "brightGreen": "#98c379", "brightYellow": "#e5c07b", "brightBlue": "#61afef", "brightMagenta": "#c678dd", "brightCyan": "#56b6c2", "brightWhite": "#ffffff", "selectionBackground": "#3e4451", "cursorColor": "#0d0f13" }
